"""add graduation fields to members

Revision ID: 18785ef25484
Revises: 0ec7b6ac7f85
Create Date: 2026-08-02 18:27:02.034393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18785ef25484'
down_revision = '0ec7b6ac7f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduation_year', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('graduation_date', sa.Date(), nullable=True))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###



    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('graduation_date')
        batch_op.drop_column('graduation_year')

    # ### end Alembic commands ###
