"""Change complaint assignment from users to executives

Revision ID: 29d357ee281c
Revises: ea2371c909fe
Create Date: 2026-07-30 21:17:23.994232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d357ee281c'
down_revision = 'ea2371c909fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversations_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('feedback_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'executives', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('feedback_ibfk_2'), 'users', ['assigned_to'], ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversations_ibfk_1'), 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###
