"""Add payment approval fields

Revision ID: 74205a6669c7
Revises: a0e218691496
Create Date: 2026-07-21 20:54:37.533138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74205a6669c7'
down_revision = 'a0e218691496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_announcements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'members', ['created_by'], ['id'])

    with op.batch_alter_table('executives', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_executive_member'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('proof_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('remarks')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('proof_image')
        batch_op.drop_column('status')

    with op.batch_alter_table('executives', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_executive_member'), 'members', ['member_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    with op.batch_alter_table('class_announcements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
