"""add academic configuration to system settings

Revision ID: ac10ab3124d9
Revises: 18785ef25484
Create Date: 2026-08-03 11:17:44.155181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac10ab3124d9'
down_revision = '18785ef25484'
branch_labels = None
depends_on = None


def upgrade():


    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_academic_year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_semester', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_session', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('current_session')
        batch_op.drop_column('current_semester')
        batch_op.drop_column('current_academic_year')



    # ### end Alembic commands ###
