"""add chat settings

Revision ID: aeca6b1659c3
Revises: 74205a6669c7
Create Date: 2026-07-23 22:41:06.256330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aeca6b1659c3'
down_revision = '74205a6669c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slides')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reply_message'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'messages', ['reply_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reply_message'), 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')

    op.create_table('slides',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('subtitle', mysql.TEXT(), nullable=True),
    sa.Column('button_text', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('button_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('display_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
