"""Change class notice author to user

Revision ID: ea2371c909fe
Revises: 9674e4ada797
Create Date: 2026-07-27 10:21:31.616917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea2371c909fe'
down_revision = '9674e4ada797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_notices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('class_notices_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['id'])
        batch_op.drop_column('author_member_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_notices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_member_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('class_notices_ibfk_2'), 'members', ['author_member_id'], ['id'])
        batch_op.drop_column('created_by_user_id')

    # ### end Alembic commands ###
